version: '3.8'
services:
  tts:
    build:
      context: ../../
      dockerfile: dockers/whisper_docker/Dockerfile

    image: whisper-service
    runtime: nvidia
    container_name: whisper-service-container
    ports:
      - "8013:8013"
    volumes:
        - /home/amitli/repo/VoiceOperation/models:/app/models
    environment:
      - PULSE_SERVER=unix:/tmp/pulse/native
      - PULSE_COOKIE=/tmp/pulse/cookie
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      #- HF_HOME=/root/.cache/huggingface
      #- TRANSFORMERS_CACHE=/root/.cache/huggingface/transformers
    devices:
      - /dev/snd



    #restart: unless-stopped