version: '3.8'
services:
  tts:
    build:
      context: ../../
      dockerfile: dockers/tts_docker/Dockerfile
    ports:
      - "8002:8002"
    image: tts-service
    container_name: tts-service-container
    volumes:
      - /mnt/nvme/models/kokoro_model:/models/kokoro_model
    environment:
      - PULSE_SERVER=unix:/tmp/pulse/native
      - PULSE_COOKIE=/tmp/pulse/cookie
    devices:
      - /dev/snd
    #restart: unless-stopped