version: '3.8'
services:
  tts:
    build:
      context: ../../
      dockerfile: dockers/tts_docker/Dockerfile
    ports:
      - "8002:8002"
    image: tts-service
    runtime: nvidia
    container_name: tts-service-container
    volumes:
      - /home/amitli/repo/VoiceOperation/models/tts:/models/tts
    environment:
      - PULSE_SERVER=unix:/tmp/pulse/native
      - PULSE_COOKIE=/tmp/pulse/cookie
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    devices:
      - /dev/snd
